version: "3"
services:
  react-app:
    image: ./frontend
    stdin_open: true
    ports: 
      - "3000:3000"

  api-server:
  build:
    context: ./backend
    ports:
      - "4000:4000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
  build:
    context: ./mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local